<?php
include 'includes/session.php';
 $apiKey = "rzp_test_YTji4Pa4Tvcpiu";
 $con=mysqli_connect('localhost','root','','props');
?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>


<form action="thankyou.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_SESSION['amount'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Prentii"
    data-description="Rent Now!!"
    data-image="\images\kavyagowda.jpg"
    data-prefill.name="Firstname"
    data-prefill.email=""
    data-prefill.contact="Enter Your Phone Number>"
    data-theme.color="#24487f"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>